a=int(input("Enter the value of a:"))
b=int(input("Enter the value for b:"))
print("="*30)
print("\t\tArithmetic operator")
print("="*30)
print("\t\tsum({},{})={}".format(a,b,a+b))
print("\t\tsub({},{})={}".format(a,b,a-b))
print("\t\tmul({},{})={}".format(a,b,a*b))
print("\t\tdiv({},{})={}".format(a,b,a/b))
print("\t\tfloordiv({},{})={}".format(a,b,a//b))
print("\t\tmodDiv({},{})={}".format(a,b,a%b))
print("\t\tpow({},{})={}".format(a,b,a**b))
print("="*30)
